version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: tiny-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tiny-admin
    volumes:
      - ./mysql:/var/lib/mysql